logging:
  config: classpath:config/logback-dev.xml
xxl:
  conf:
    zkaddress: 127.0.0.1:2181
    zkpath: /xxl-conf
    envprop:
      location: null
    localprop:
      location: null
  job:
    admin: 
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip: null
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: null
