logging:
  config: classpath:config/logback-dev.xml
 
spring:
  datasource:
    name: dago
    url: jdbc:mysql://172.31.28.101:3306/dago?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: rzx!@!*wh
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# xxl-conf
xxl:
  conf:
    zkaddress: 127.0.0.1:2181
    zkdigest: /xxl-conf
      
      
      