spring:
  profiles:
    active: dev
  application: 
    name: dago-application
    description: dago平台接口
    version: 0.0.1-SNAPSHOT

management: 
  security: 
    enabled: true


info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

server:
  port: 8080