logging:
  config: classpath:config/logback-dev.xml
  
spring:
  datasource:
    name: dago
    url: jdbc:mysql://172.31.28.101:3306/dago?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull 
    username: root
    password: 123456