spring:
  profiles:
    active: dev
  application:
    name: dago-application
    description: dago平台接口
    version: 1.0
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
mybatis:
  config-locations: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.surfilter.ps.**.entity
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
org:
  quartz:
    scheduler:
      wrapJobExecutionInUserTransaction: false
      instanceName: DefaultQuartzScheduler
    rmi:
      export: false
      proxy: false
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5 # 并发个数
      threadPriority: 5 # 优先级
      threadsInheritContextClassLoaderOfInitializingThread: true
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      tablePrefix: QRTZ_
      misfireThreshold: 5000
      dataSource: qzDS
server:
  port: 8080