spring:
  profiles:
    active: prod
  application:
    name: dago-application
    description: dago平台接口
    version: 0.0.1-SNAPSHOT
management:
  security:
    enabled: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8080