spring:
  profiles:
    active: dev
  application:
    name: dago-application
    description: dago平台接口
    version: 0.0.1-SNAPSHOT
management:
  security:
    enabled: true
mybatis:
  config-locations: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.surfilter.ps.**.entity
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8080