logging:
  config: classpath:config/logback-dev.xml

spring:
  datasource:
    name: dago
    url: jdbc:mysql://172.31.28.101:3306/dago?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull 
    username: root
    password: 123456

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: rzx1218
    key-store-type: PKCS12
    key-alias: tomcat